/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import model.Episodio;
import javax.swing.JOptionPane;
import servicios.ServicioContenido;

/**
 *
 * @author Juan Murcia
 */
public class GUIActualizarEpisodio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIActualizarEpisodio.class.getName());
    private final ServicioContenido servicio;

    /**
     * Creates new form GUIActualizarEpisodio
     */
    public GUIActualizarEpisodio() {
        initComponents();
        servicio = ServicioContenido.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNuevoTitulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBuscarEpisodio = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdSerie = new javax.swing.JTextField();
        txtNoEpisodio = new javax.swing.JTextField();
        btnActualizarEpisodio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtNuevoTitulo.setEditable(false);
        txtNuevoTitulo.addActionListener(this::txtNuevoTituloActionPerformed);

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Actualizar episodio");

        btnBuscarEpisodio.setText("Buscar");
        btnBuscarEpisodio.addActionListener(this::btnBuscarEpisodioActionPerformed);

        jLabel4.setText("ID de la Serie:");

        jLabel5.setText("No. Episodio:");

        jLabel6.setText("Nuevo titulo:");

        btnActualizarEpisodio.setText("Actualizar");
        btnActualizarEpisodio.setEnabled(false);
        btnActualizarEpisodio.addActionListener(this::btnActualizarEpisodioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarEpisodio, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNuevoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarEpisodio, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdSerie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoEpisodio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarEpisodio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNuevoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnActualizarEpisodio)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNuevoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNuevoTituloActionPerformed

    private void btnBuscarEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEpisodioActionPerformed
        btnActualizarEpisodio.setEnabled(false);
        txtNuevoTitulo.setEditable(false);

        String idSerie = txtIdSerie.getText().trim();
        String noEpisodioStr = txtNoEpisodio.getText().trim();

        if (idSerie.isEmpty() || noEpisodioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la serie y el número de episodio.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int noEpisodio = Integer.parseInt(noEpisodioStr);
            Episodio ep = servicio.searchEpisodio(idSerie, noEpisodio);

            txtNuevoTitulo.setText(ep.getTitulo());
            txtNuevoTitulo.setEditable(true);
            txtIdSerie.setEditable(false);   // se bloquea: no tiene sentido "mover" el episodio de serie
            txtNoEpisodio.setEditable(false); // ni cambiar su número mientras se actualiza el título
            btnActualizarEpisodio.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Episodio encontrado.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de episodio debe ser un valor numérico.",
                    "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Sin Resultados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarEpisodioActionPerformed

    private void btnActualizarEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEpisodioActionPerformed
        try {
            String idSerie = txtIdSerie.getText().trim();
            int noEpisodio = Integer.parseInt(txtNoEpisodio.getText().trim());
            String nuevoTitulo = txtNuevoTitulo.getText().trim();

            if (nuevoTitulo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El título no puede estar vacío.",
                        "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            servicio.updateEpisodio(idSerie, noEpisodio, nuevoTitulo);
            JOptionPane.showMessageDialog(this, "Episodio actualizado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarEpisodioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIActualizarEpisodio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEpisodio;
    private javax.swing.JButton btnBuscarEpisodio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtIdSerie;
    private javax.swing.JTextField txtNoEpisodio;
    private javax.swing.JTextField txtNuevoTitulo;
    // End of variables declaration//GEN-END:variables
}
