/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Model.Serie;
import javax.swing.JOptionPane;
import servicios.ServicioContenido;

/**
 *
 * @author jamed
 */
public class GUIActualizarSerie extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIActualizarSerie.class.getName());

    /**
     * Creates new form GUIActualizarSerie
     */
    public GUIActualizarSerie() {
        initComponents();
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
    }
    
    private void limpiarCampos() {
        txtID.setText("");
        txtTitulo.setText("");
        txtDuracion.setText("");
        txtCalificacion.setText("");
        jDateChooser1.setDate(null);
        txtTemporadas.setText("");
        txtEpisodiosPorTemporada.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtTemporadas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEpisodiosPorTemporada = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        btnBuscarSerie = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCalificacion = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnActualizarSerie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Serie");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel5.setText("Fecha Estreno:");

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel8.setText("actualizar SERIE");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel6.setText("Temporadas:");

        txtTemporadas.addActionListener(this::txtTemporadasActionPerformed);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel7.setText("Total Episodios:");

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel1.setText("Título:");

        btnBuscarSerie.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBuscarSerie.setText("Buscar");
        btnBuscarSerie.addActionListener(this::btnBuscarSerieActionPerformed);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel3.setText("Duración:");

        txtDuracion.addActionListener(this::txtDuracionActionPerformed);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel4.setText("Calificación:");

        btnActualizarSerie.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnActualizarSerie.setText("Actualizar");
        btnActualizarSerie.addActionListener(this::btnActualizarSerieActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCalificacion)))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(54, 54, 54)
                        .addComponent(txtDuracion))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(txtTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtEpisodiosPorTemporada))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(90, 90, 90)
                        .addComponent(txtID))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(txtTemporadas)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnBuscarSerie)
                        .addGap(56, 56, 56)
                        .addComponent(btnActualizarSerie))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel8)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEpisodiosPorTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarSerie)
                    .addComponent(btnActualizarSerie))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTemporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemporadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemporadasActionPerformed

    private void btnBuscarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSerieActionPerformed
        String id = txtID.getText().trim();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingrese el ID de la serie a buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    Serie s = ServicioContenido.getInstance().searchSerie(id);

    if (s != null) {
        txtTitulo.setText(s.getTitulo());
        txtDuracion.setText(String.valueOf(s.getDuracionMinutos()));
        txtCalificacion.setText(String.valueOf(s.getCalificacion()));
        txtTemporadas.setText(String.valueOf(s.getTemporadas()));
        txtEpisodiosPorTemporada.setText(String.valueOf(s.getEpisodios()));

        if (s.getFechaEstreno() != null) {
            java.util.Date fechaDate = java.util.Date.from(
                s.getFechaEstreno().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()
            );
            jDateChooser1.setDate(fechaDate);
        } else {
            jDateChooser1.setDate(null);
        }

        // Bloquear el ID para proteger la llave primaria
        txtID.setEditable(false);
        JOptionPane.showMessageDialog(this, "Serie encontrada.", "Información", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró ninguna serie con el ID proporcionado.", "Sin Resultados", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBuscarSerieActionPerformed

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void btnActualizarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSerieActionPerformed
        try {
        // 1. Capturar datos base
        String id = txtID.getText().trim();
        String titulo = txtTitulo.getText().trim();
        String duracionStr = txtDuracion.getText().trim();
        String calificacionStr = txtCalificacion.getText().trim();
        String temporadasStr = txtTemporadas.getText().trim();
        String episodiosStr = txtEpisodiosPorTemporada.getText().trim();

        // Capturar Fecha del JDateChooser
        java.util.Date fechaSeleccionada = jDateChooser1.getDate();

        // 2. Validaciones
        if (id.isEmpty() || titulo.isEmpty() || duracionStr.isEmpty()
                || calificacionStr.isEmpty() || temporadasStr.isEmpty() 
                || episodiosStr.isEmpty() || fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos, incluida la fecha de estreno.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Convertir java.util.Date a java.time.LocalDate
        java.time.LocalDate fechaEstreno = fechaSeleccionada.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();

        // Parsear datos numéricos
        int duracion = Integer.parseInt(duracionStr);
        double calificacion = Double.parseDouble(calificacionStr);
        int temporadas = Integer.parseInt(temporadasStr);
        int episodios = Integer.parseInt(episodiosStr);

        if (calificacion < 0.0 || calificacion > 10.0) {
            JOptionPane.showMessageDialog(this,
                    "La calificación debe ser un valor entre 0.0 y 10.0",
                    "Calificación Inválida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Construir la entidad Serie usando Builder
        Serie serieActualizada = Serie.builder()
                .id(id)
                .titulo(titulo)
                .duracionMinutos(duracion)
                .calificacion(calificacion)
                .fechaEstreno(fechaEstreno)
                .temporadas(temporadas)
                .episodios(episodios)
                .build();

        // 4. Invocar actualización en el Servicio
        ServicioContenido.getInstance().updateContenido(serieActualizada);

        JOptionPane.showMessageDialog(this, "Serie actualizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
        txtID.setEditable(true);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La duración, calificación, temporadas y episodios deben ser valores numéricos válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnActualizarSerieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIActualizarSerie().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarSerie;
    private javax.swing.JButton btnBuscarSerie;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEpisodiosPorTemporada;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTemporadas;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
