/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Model.Pelicula;
import javax.swing.JOptionPane;
import servicios.ServicioContenido;

/**
 *
 * @author jamed
 */
public class GUIActualizarPelicula extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIActualizarPelicula.class.getName());
    private final ServicioContenido servicio;

    /**
     * Creates new form GUIActualizarPelicula
     */
    public GUIActualizarPelicula() {
        initComponents();
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
        servicio = ServicioContenido.getInstance();
    }

    private void limpiarCampos() {
        txtID1.setText("");
        txtTitulo.setText("");
        txtDuracion.setText("");
        txtCalificacion.setText("");
        jDateChooser1.setDate(null);
        txtRecaudacion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtRecaudacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbEsSaga = new javax.swing.JComboBox<>();
        txtTitulo = new javax.swing.JTextField();
        txtID1 = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        txtCalificacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnActualizarPelicula = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBuscarPelicula = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Pelicula");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel4.setText("Calificación:");

        txtRecaudacion.setToolTipText("0 si salio exclusivamente para plataformas");
        txtRecaudacion.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel5.setText("Fecha Estreno:");

        cmbEsSaga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        cmbEsSaga.setEnabled(false);

        txtTitulo.setEnabled(false);

        txtDuracion.setEnabled(false);
        txtDuracion.addActionListener(this::txtDuracionActionPerformed);

        txtCalificacion.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Actualizar Película");

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel1.setText("Título:");

        btnActualizarPelicula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnActualizarPelicula.setText("Actualizar");
        btnActualizarPelicula.setEnabled(false);
        btnActualizarPelicula.addActionListener(this::btnActualizarPeliculaActionPerformed);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel9.setText("Saga: ");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel3.setText("Duración:");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel10.setText("Recaudación Taquilla: ");

        btnBuscarPelicula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBuscarPelicula.setText("Buscar");
        btnBuscarPelicula.addActionListener(this::btnBuscarPeliculaActionPerformed);

        jDateChooser1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbEsSaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(159, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarPelicula))
                            .addComponent(txtTitulo)
                            .addComponent(txtDuracion)
                            .addComponent(txtRecaudacion)
                            .addComponent(txtCalificacion, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarPelicula)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscarPelicula))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbEsSaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnActualizarPelicula)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void btnActualizarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPeliculaActionPerformed
        try {
            // 1. Capturar datos base
            String id = txtID1.getText().trim();
            String titulo = txtTitulo.getText().trim();
            String duracionStr = txtDuracion.getText().trim();
            String calificacionStr = txtCalificacion.getText().trim();
            String taquillaStr = txtRecaudacion.getText().trim();

            // JComboBox para esSaga
            String sagaSeleccion = cmbEsSaga.getSelectedItem().toString();
            boolean esSaga = sagaSeleccion.equalsIgnoreCase("Sí");

            // Capturar Fecha del JDateChooser
            java.util.Date fechaSeleccionada = jDateChooser1.getDate();

            // 2. Validaciones
            if (id.isEmpty() || titulo.isEmpty() || duracionStr.isEmpty()
                    || calificacionStr.isEmpty() || taquillaStr.isEmpty() || fechaSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Por favor complete todos los campos, incluida la fecha de estreno.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Convertir java.util.Date a java.time.LocalDate
            java.time.LocalDate fechaEstreno = fechaSeleccionada.toInstant()
                    .atZone(java.time.ZoneId.systemDefault())
                    .toLocalDate();

            // Parsear datos numéricos
            int duracion = Integer.parseInt(duracionStr);
            double calificacion = Double.parseDouble(calificacionStr);

            if (calificacion < 0.0 || calificacion > 10.0) {
                JOptionPane.showMessageDialog(this,
                        "La calificación debe ser un valor entre 0.0 y 10.0",
                        "Calificación Inválida",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            double recaudacionTaquilla = Double.parseDouble(taquillaStr);

            // 3. Construir el objeto actualizado usando Builder
            Pelicula peliculaActualizada = Pelicula.builder()
                    .id(id)
                    .titulo(titulo)
                    .duracionMinutos(duracion)
                    .calificacion(calificacion)
                    .fechaEstreno(fechaEstreno)
                    .esSaga(esSaga)
                    .recaudacionTaquilla(recaudacionTaquilla)
                    .build();

            servicio.updateContenido(peliculaActualizada);

            JOptionPane.showMessageDialog(this, "Película actualizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            txtID1.setEditable(true);
            disableCampos();
            btnActualizarPelicula.setEnabled(false);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La duración, calificación y taquilla deben ser valores numéricos válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarPeliculaActionPerformed

    private void enableCampos() {
        txtTitulo.setEnabled(true);
        txtDuracion.setEnabled(true);
        txtCalificacion.setEnabled(true);
        cmbEsSaga.setEnabled(true);
        txtRecaudacion.setEnabled(true);
        jDateChooser1.setEnabled(true);
    }

    private void disableCampos() {
        txtTitulo.setEnabled(false);
        txtDuracion.setEnabled(false);
        txtCalificacion.setEnabled(false);
        cmbEsSaga.setEnabled(false);
        txtRecaudacion.setEnabled(false);
        jDateChooser1.setEnabled(false);
    }

    private void btnBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPeliculaActionPerformed
        String id = txtID1.getText().trim();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el ID de la película a buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            Pelicula p = servicio.searchPelicula(id);

            if (p != null) {
                // Llenar campos con la información encontrada
                txtTitulo.setText(p.getTitulo());
                txtDuracion.setText(String.valueOf(p.getDuracionMinutos()));
                txtCalificacion.setText(String.valueOf(p.getCalificacion()));
                cmbEsSaga.setSelectedItem(p.isEsSaga() ? "Sí" : "No");
                txtRecaudacion.setText(String.valueOf(p.getRecaudacionTaquilla()));

                if (p.getFechaEstreno() != null) {
                    java.util.Date fechaDate = java.util.Date.from(
                            p.getFechaEstreno().atStartOfDay(java.time.ZoneId.systemDefault()).toInstant()
                    );
                    jDateChooser1.setDate(fechaDate);
                } else {
                    jDateChooser1.setDate(null);
                }

                txtID1.setEditable(false);
                JOptionPane.showMessageDialog(this, "Película encontrada.", "Información", JOptionPane.INFORMATION_MESSAGE);
                enableCampos();
                btnActualizarPelicula.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ninguna película con el ID proporcionado.", "Sin Resultados", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnBuscarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIActualizarPelicula().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPelicula;
    private javax.swing.JButton btnBuscarPelicula;
    private javax.swing.JComboBox<String> cmbEsSaga;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtRecaudacion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
