/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Model.Episodio;
import javax.swing.JOptionPane;
import servicios.ServicioContenido;

/**
 *
 * @author Alejandra Murcia
 */
public class GUIEliminarEpisodio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIEliminarEpisodio.class.getName());
    private final ServicioContenido servicio;

    /**
     * Creates new form GUIEliminarEpisodio
     */
    public GUIEliminarEpisodio() {
        initComponents();
        servicio = ServicioContenido.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdSerie = new javax.swing.JTextField();
        txtNoEpisodio = new javax.swing.JTextField();
        btnBuscarEpisodio = new javax.swing.JButton();
        btnBorrarEpisodio = new javax.swing.JButton();
        lblResultadoTitulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Eliminar episodio");

        jLabel1.setText("ID de la Serie:");

        jLabel2.setText("No. Episodio:");

        jLabel3.setText("Titulo: ");

        txtIdSerie.addActionListener(this::txtIdSerieActionPerformed);

        btnBuscarEpisodio.setText("Buscar");
        btnBuscarEpisodio.addActionListener(this::btnBuscarEpisodioActionPerformed);

        btnBorrarEpisodio.setText("Eliminar");
        btnBorrarEpisodio.addActionListener(this::btnBorrarEpisodioActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdSerie, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNoEpisodio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(btnBuscarEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrarEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarEpisodio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultadoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrarEpisodio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSerieActionPerformed

    private void btnBuscarEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEpisodioActionPerformed
        String idSerie = txtIdSerie.getText().trim();
        String noEpisodioStr = txtNoEpisodio.getText().trim();

        if (idSerie.isEmpty() || noEpisodioStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la serie y el número de episodio.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            btnBorrarEpisodio.setEnabled(false);
            int noEpisodio = Integer.parseInt(noEpisodioStr);
            Episodio ep = servicio.searchEpisodio(idSerie, noEpisodio);

            lblResultadoTitulo.setText(ep.getTitulo());
            btnBorrarEpisodio.setEnabled(true);
        } catch (NumberFormatException e) {
            limpiarLabel();
            JOptionPane.showMessageDialog(this, "El número de episodio debe ser un valor numérico.",
                    "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            limpiarLabel();
            JOptionPane.showMessageDialog(this, e.getMessage(), "No encontrado", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarLabel() {
        lblResultadoTitulo.setText("Título: -");
    }//GEN-LAST:event_btnBuscarEpisodioActionPerformed

    private void btnBorrarEpisodioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEpisodioActionPerformed
    String idSerie = txtIdSerie.getText().trim();
    int noEpisodio = Integer.parseInt(txtNoEpisodio.getText().trim());

    int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea eliminar este episodio?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            servicio.delEpisodioDeSerie(idSerie, noEpisodio);

            txtIdSerie.setText("");
            txtNoEpisodio.setText("");
            limpiarLabel();
            btnBorrarEpisodio.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Episodio eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnBorrarEpisodioActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIEliminarEpisodio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarEpisodio;
    private javax.swing.JButton btnBuscarEpisodio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lblResultadoTitulo;
    private javax.swing.JTextField txtIdSerie;
    private javax.swing.JTextField txtNoEpisodio;
    // End of variables declaration//GEN-END:variables
}
