/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Model.Pelicula;
import javax.swing.JOptionPane;
import servicios.ServicioContenido;

/**
 *
 * @author Dan
 */
public class GUIEliminarPelicula extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIEliminarPelicula.class.getName());

    /**
     * Creates new form GUIEliminarSerie
     */
    public GUIEliminarPelicula() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnBuscarPelicula = new javax.swing.JButton();
        btnBorrarPelicula = new javax.swing.JButton();
        lblResultadoTitulo = new javax.swing.JLabel();
        lblResultadoDuracion = new javax.swing.JLabel();
        lblResultadoCalificacion = new javax.swing.JLabel();
        lblResultadoEstreno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminación");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Eliminar Pelicula");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel7.setText("Ingrese la ID de la película a eliminar");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBuscarPelicula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBuscarPelicula.setText("Buscar");
        btnBuscarPelicula.addActionListener(this::btnBuscarPeliculaActionPerformed);

        btnBorrarPelicula.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBorrarPelicula.setText("Borrar");
        btnBorrarPelicula.addActionListener(this::btnBorrarPeliculaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(btnBuscarPelicula)
                            .addGap(45, 45, 45)
                            .addComponent(btnBorrarPelicula))
                        .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(txtID, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultadoEstreno)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblResultadoDuracion)
                                .addComponent(lblResultadoTitulo)
                                .addComponent(lblResultadoCalificacion)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoDuracion)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoCalificacion)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoEstreno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPelicula)
                    .addComponent(btnBorrarPelicula))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPeliculaActionPerformed
        String id = txtID.getText().trim();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese la ID a buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        btnBorrarPelicula.setEnabled(false);
        Pelicula p = ServicioContenido.getInstance().searchPelicula(id);

        lblResultadoTitulo.setText("Título: " + p.getTitulo());
        lblResultadoDuracion.setText("Duración: " + p.getDuracionMinutos() + " min");
        lblResultadoCalificacion.setText("Calificación: " + p.getCalificacion() + " ★");

        btnBorrarPelicula.setEnabled(true);

    } catch (IllegalArgumentException e) {
        // Si no se encuentra, limpiamos los labels y mostramos error
        limpiarLabels();
        btnBorrarPelicula.setEnabled(false);
        JOptionPane.showMessageDialog(this, e.getMessage(), "No encontrado", JOptionPane.ERROR_MESSAGE);
    }
}

private void limpiarLabels() {
    lblResultadoTitulo.setText("Título: -");
    lblResultadoDuracion.setText("Duración: -");
    lblResultadoCalificacion.setText("Calificación: -");
    }//GEN-LAST:event_btnBuscarPeliculaActionPerformed

    private void btnBorrarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPeliculaActionPerformed
       String id = txtID.getText().trim();

    int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea eliminar esta película?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            ServicioContenido.getInstance().delPelicula(id);
            
            // Limpieza tras eliminar
            txtID.setText("");
            limpiarLabels();
            btnBorrarPelicula.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Película eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnBorrarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIEliminarPelicula().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarPelicula;
    private javax.swing.JButton btnBuscarPelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblResultadoCalificacion;
    private javax.swing.JLabel lblResultadoDuracion;
    private javax.swing.JLabel lblResultadoEstreno;
    private javax.swing.JLabel lblResultadoTitulo;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
