/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Model.Serie;
import javax.swing.JOptionPane;
import servicios.ServicioContenido;

/**
 *
 * @author Dan
 */
public class GUIEliminarSerie extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIEliminarSerie.class.getName());

    /**
     * Creates new form GUIEliminarSerie
     */
    public GUIEliminarSerie() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    
    private void limpiarCampos() {
        txtID.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnBorrarSerie = new javax.swing.JButton();
        btnBuscarSerie = new javax.swing.JButton();
        lblResultadoTitulo = new javax.swing.JLabel();
        lblResultadoDuracion = new javax.swing.JLabel();
        lblResultadoCalificacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminación");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Eliminar serie");

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel7.setText("Ingrese la ID de la serie a eliminar");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBorrarSerie.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBorrarSerie.setText("Borrar");
        btnBorrarSerie.addActionListener(this::btnBorrarSerieActionPerformed);

        btnBuscarSerie.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnBuscarSerie.setText("Buscar");
        btnBuscarSerie.addActionListener(this::btnBuscarSerieActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBuscarSerie)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBorrarSerie))
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblResultadoTitulo)
                            .addComponent(lblResultadoDuracion)
                            .addComponent(lblResultadoCalificacion))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoDuracion)
                .addGap(18, 18, 18)
                .addComponent(lblResultadoCalificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarSerie)
                    .addComponent(btnBuscarSerie))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarSerieActionPerformed
        String id = txtID.getText().trim();

    int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea eliminar esta serie?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            ServicioContenido.getInstance().delSerie(id);
            
            // Limpieza tras eliminar
            txtID.setText("");
            limpiarLabels();
            btnBorrarSerie.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Película eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnBorrarSerieActionPerformed

    private void btnBuscarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSerieActionPerformed
        String id = txtID.getText().trim();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese la ID a buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        btnBorrarSerie.setEnabled(false);
        Serie s = ServicioContenido.getInstance().searchSerie(id);

        // Actualizamos los Labels
        lblResultadoTitulo.setText("Título: " + s.getTitulo());
        lblResultadoDuracion.setText("Duración: " + s.getDuracionMinutos() + " min");
        lblResultadoCalificacion.setText("Calificación: " + s.getCalificacion() + " ★");

        btnBorrarSerie.setEnabled(true);

    } catch (IllegalArgumentException e) {
        limpiarLabels();
        btnBorrarSerie.setEnabled(false);
        JOptionPane.showMessageDialog(this, e.getMessage(), "No encontrado", JOptionPane.ERROR_MESSAGE);
    }
    }
    private void limpiarLabels() {
    lblResultadoTitulo.setText("Título: -");
    lblResultadoDuracion.setText("Duración: -");
    lblResultadoCalificacion.setText("Calificación: -");
    }//GEN-LAST:event_btnBuscarSerieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIEliminarSerie().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarSerie;
    private javax.swing.JButton btnBuscarSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblResultadoCalificacion;
    private javax.swing.JLabel lblResultadoDuracion;
    private javax.swing.JLabel lblResultadoTitulo;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
