/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author jamed
 */
public class GUIListarContenido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIListarContenido.class.getName());

    /**
     * Creates new form GUIListarContenido
     */
    public GUIListarContenido() {
        initComponents();
        this.setResizable(false);
        this.pack(); 
        this.setLocationRelativeTo(null);
        cargarTabla("TODOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaContenidos = new javax.swing.JTable();
        btnTodos = new javax.swing.JButton();
        btnSeries = new javax.swing.JButton();
        btnPeliculas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contenido De Aniflex");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("CONTENIDO DE ANIFLEX");

        TablaContenidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Fecha Estreno", "Title 4", "null"
            }
        ));
        jScrollPane1.setViewportView(TablaContenidos);

        btnTodos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnTodos.setText("Ver Todo");
        btnTodos.addActionListener(this::btnTodosActionPerformed);

        btnSeries.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSeries.setText("Series");
        btnSeries.addActionListener(this::btnSeriesActionPerformed);

        btnPeliculas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnPeliculas.setText("Películas");
        btnPeliculas.addActionListener(this::btnPeliculasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTodos)
                                .addGap(95, 95, 95)
                                .addComponent(btnSeries)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPeliculas))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodos)
                    .addComponent(btnSeries)
                    .addComponent(btnPeliculas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        cargarTabla("TODOS");
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeliculasActionPerformed
        cargarTabla("PELICULAS");
    }//GEN-LAST:event_btnPeliculasActionPerformed

    private void btnSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeriesActionPerformed
        cargarTabla("SERIES");
    }//GEN-LAST:event_btnSeriesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIListarContenido().setVisible(true));
    }
    
    public void cargarTabla(String filtro) {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();

    // 1. Configurar Títulos de las Columnas según el Filtro
    if (filtro.equals("PELICULAS")) {
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Título", "Calificación", "Fecha Estreno", "Duración", "Director", "Presupuesto"
        });
    } else if (filtro.equals("SERIES")) {
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Título", "Calificación", "Fecha Estreno", "Duración", "Temporadas", "Eps / Temp"
        });
    } else { // "TODOS"
        modelo.setColumnIdentifiers(new Object[]{
            "ID", "Tipo", "Título", "Calificación", "Fecha Estreno", "Duración", "Detalles Específicos"
        });
    }

    // 2. Llenar Datos de Películas
    if (filtro.equals("PELICULAS") || filtro.equals("TODOS")) {
        for (Model.Pelicula p : Servicio.ServicioPelicula.listar()) {
            String fecha = (p.getFechaEstreno() != null) ? sdf.format(p.getFechaEstreno()) : "";
            
            if (filtro.equals("PELICULAS")) {
                modelo.addRow(new Object[]{
                    p.getId(), 
                    p.getTitulo(), 
                    p.getCalificacion(), 
                    fecha, 
                    p.getDuracionMinutos() + " min", 
                    p.getDirector(), 
                    "$" + p.getPresupuesto()
                });
            } else { // En la vista "TODOS" los consolida de forma clara
                modelo.addRow(new Object[]{
                    p.getId(), 
                    "Película", 
                    p.getTitulo(), 
                    p.getCalificacion(), 
                    fecha, 
                    p.getDuracionMinutos() + " min", 
                    "Director: " + p.getDirector()
                });
            }
        }
    }

    // 3. Llenar Datos de Series
    if (filtro.equals("SERIES") || filtro.equals("TODOS")) {
        for (Model.Serie s : Servicio.ServicioSerie.listar()) {
            String fecha = (s.getFechaEstreno() != null) ? sdf.format(s.getFechaEstreno()) : "";
            
            if (filtro.equals("SERIES")) {
                modelo.addRow(new Object[]{
                    s.getId(), 
                    s.getTitulo(), 
                    s.getCalificacion(), 
                    fecha, 
                    s.getDuracionMinutos() + " min", 
                    s.getTemporadas(), 
                    s.getEpisodiosPorTemporada()
                });
            } else { // En la vista "TODOS"
                modelo.addRow(new Object[]{
                    s.getId(), 
                    "Serie", 
                    s.getTitulo(), 
                    s.getCalificacion(), 
                    fecha, 
                    s.getDuracionMinutos() + " min", 
                    s.getTemporadas() + " Temp. / " + s.getEpisodiosPorTemporada() + " Eps"
                });
            }
        }
    }

    // 4. Asignar el modelo actualizado a tu JTable
    TablaContenidos.setModel(modelo);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaContenidos;
    private javax.swing.JButton btnPeliculas;
    private javax.swing.JButton btnSeries;
    private javax.swing.JButton btnTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
