/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import interfaz.GUIBuscarSerie;
import interfaz.GUICalcularRetencionPelicula;
import interfaz.GUICalcularRetencionSerie;
import interfaz.GUIEliminarPelicula;
import interfaz.GUIEliminarSerie;

/**
 *
 * @author jamed
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        this.setResizable(false);
        this.pack(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jAdicionarPelicula = new javax.swing.JMenuItem();
        jListarPelicula = new javax.swing.JMenuItem();
        jBuscarPelicula = new javax.swing.JMenuItem();
        jEliminarPelicula = new javax.swing.JMenuItem();
        jMenuItemCalculoPeli = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jAdicionarSerie = new javax.swing.JMenuItem();
        jListarSerie = new javax.swing.JMenuItem();
        jBuscarSerie = new javax.swing.JMenuItem();
        jEliminarSerie = new javax.swing.JMenuItem();
        jMenuItemCalculoSerie = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aniflex-logo(1)(1).png"))); // NOI18N

        jMenu1.setText("Archivo");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(this::jMenuItemSalirActionPerformed);
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Película");

        jAdicionarPelicula.setText("Adicionar");
        jAdicionarPelicula.addActionListener(this::jAdicionarPeliculaActionPerformed);
        jMenu2.add(jAdicionarPelicula);

        jListarPelicula.setText("Listar");
        jListarPelicula.addActionListener(this::jListarPeliculaActionPerformed);
        jMenu2.add(jListarPelicula);

        jBuscarPelicula.setText("Buscar");
        jBuscarPelicula.addActionListener(this::jBuscarPeliculaActionPerformed);
        jMenu2.add(jBuscarPelicula);

        jEliminarPelicula.setText("Eliminar");
        jEliminarPelicula.addActionListener(this::jEliminarPeliculaActionPerformed);
        jMenu2.add(jEliminarPelicula);

        jMenuItemCalculoPeli.setText("Calcular retención");
        jMenuItemCalculoPeli.addActionListener(this::jMenuItemCalculoPeliActionPerformed);
        jMenu2.add(jMenuItemCalculoPeli);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Serie");

        jAdicionarSerie.setText("Adicionar");
        jAdicionarSerie.addActionListener(this::jAdicionarSerieActionPerformed);
        jMenu3.add(jAdicionarSerie);

        jListarSerie.setText("Listar");
        jListarSerie.addActionListener(this::jListarSerieActionPerformed);
        jMenu3.add(jListarSerie);

        jBuscarSerie.setText("Buscar");
        jBuscarSerie.addActionListener(this::jBuscarSerieActionPerformed);
        jMenu3.add(jBuscarSerie);

        jEliminarSerie.setText("Eliminar");
        jEliminarSerie.addActionListener(this::jEliminarSerieActionPerformed);
        jMenu3.add(jEliminarSerie);

        jMenuItemCalculoSerie.setText("Calcular Retención");
        jMenuItemCalculoSerie.addActionListener(this::jMenuItemCalculoSerieActionPerformed);
        jMenu3.add(jMenuItemCalculoSerie);

        jMenuBar1.add(jMenu3);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca de");
        jMenuItemAcercaDe.addActionListener(this::jMenuItemAcercaDeActionPerformed);
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAdicionarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarPeliculaActionPerformed
        GUIAdicionarPelicula ventana = new GUIAdicionarPelicula ();
        ventana.setVisible(true);
    }//GEN-LAST:event_jAdicionarPeliculaActionPerformed

    private void jListarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarPeliculaActionPerformed
        GUIListarPelicula ventana = new GUIListarPelicula ();
        ventana.setVisible(true);
    }//GEN-LAST:event_jListarPeliculaActionPerformed

    private void jBuscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarPeliculaActionPerformed
        GUIBuscarPelicula ventana = new GUIBuscarPelicula();
        ventana.setVisible(true);
    }//GEN-LAST:event_jBuscarPeliculaActionPerformed

    private void jAdicionarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarSerieActionPerformed
        GUIAdicionarSerie ventana = new GUIAdicionarSerie ();
        ventana.setVisible(true);
    }//GEN-LAST:event_jAdicionarSerieActionPerformed

    private void jListarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarSerieActionPerformed
        GUIListarSerie ventana = new GUIListarSerie ();
        ventana.setVisible(true);
    }//GEN-LAST:event_jListarSerieActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        GUIAcercaDe ventana = new GUIAcercaDe();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenuItemCalculoSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculoSerieActionPerformed
        GUICalcularRetencionSerie ventana = new GUICalcularRetencionSerie();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemCalculoSerieActionPerformed

    private void jMenuItemCalculoPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculoPeliActionPerformed
        GUICalcularRetencionPelicula ventana = new GUICalcularRetencionPelicula();
        ventana.setVisible(true);
    }//GEN-LAST:event_jMenuItemCalculoPeliActionPerformed

    private void jBuscarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarSerieActionPerformed
        GUIBuscarSerie ventana = new GUIBuscarSerie();
        ventana.setVisible(true);
    }//GEN-LAST:event_jBuscarSerieActionPerformed

    private void jEliminarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarSerieActionPerformed
        GUIEliminarSerie ventana = new GUIEliminarSerie();
        ventana.setVisible(true);
    }//GEN-LAST:event_jEliminarSerieActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jEliminarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarPeliculaActionPerformed
        GUIEliminarPelicula ventana = new GUIEliminarPelicula();
        ventana.setVisible(true);
    }//GEN-LAST:event_jEliminarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAdicionarPelicula;
    private javax.swing.JMenuItem jAdicionarSerie;
    private javax.swing.JMenuItem jBuscarPelicula;
    private javax.swing.JMenuItem jBuscarSerie;
    private javax.swing.JMenuItem jEliminarPelicula;
    private javax.swing.JMenuItem jEliminarSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jListarPelicula;
    private javax.swing.JMenuItem jListarSerie;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemCalculoPeli;
    private javax.swing.JMenuItem jMenuItemCalculoSerie;
    private javax.swing.JMenuItem jMenuItemSalir;
    // End of variables declaration//GEN-END:variables
}
