/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author jamed
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        this.setResizable(false);
        this.pack(); 
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jDeveloper = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jAdicionarContenido = new javax.swing.JMenuItem();
        jListarContenido = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio");

        jMenu1.setText("Archivo");

        jDeveloper.setText("Developers");
        jDeveloper.addActionListener(this::jDeveloperActionPerformed);
        jMenu1.add(jDeveloper);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Contenido");

        jAdicionarContenido.setText("Adicionar");
        jAdicionarContenido.addActionListener(this::jAdicionarContenidoActionPerformed);
        jMenu2.add(jAdicionarContenido);

        jListarContenido.setText("Listar");
        jListarContenido.addActionListener(this::jListarContenidoActionPerformed);
        jMenu2.add(jListarContenido);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeveloperActionPerformed
        GUIDeveloper ventana = new GUIDeveloper();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_jDeveloperActionPerformed

    private void jAdicionarContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdicionarContenidoActionPerformed
        Object[] opciones = {"Película", "Serie", "Cancelar"};

        // 2. Muestra la ventana emergente de selección
        int seleccion = javax.swing.JOptionPane.showOptionDialog(
            this,
            "¿Qué tipo de contenido deseas adicionar?",
            "Seleccionar tipo de contenido",
            javax.swing.JOptionPane.YES_NO_CANCEL_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        // 3. Abrir la ventana según la opción elegida
        if (seleccion == 0) {
            // Seleccionó "Película"
            GUIAdicionarPelicula guiPeli = new GUIAdicionarPelicula();
            guiPeli.setVisible(true);
        } else if (seleccion == 1) {
            // Seleccionó "Serie"
            GUIAdicionarSerie guiSerie = new GUIAdicionarSerie();
            guiSerie.setVisible(true);
        }
    }//GEN-LAST:event_jAdicionarContenidoActionPerformed

    private void jListarContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListarContenidoActionPerformed
        GUIListarContenido ventana = new GUIListarContenido ();
        ventana.setVisible(true);
    }//GEN-LAST:event_jListarContenidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAdicionarContenido;
    private javax.swing.JMenuItem jDeveloper;
    private javax.swing.JMenuItem jListarContenido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
